### PR TITLE
Support for multiple use-cases in one config

### LINKED ISSUE #518: re-introduce support for multiple detection use cases in single configuration file
key driver to do this is to make it compatible with sigmac

### PR DESCRIPTION
**Pull request by SpeedyFireCyclone**
These changes allow for multiple use-cases in a single config by adding a `create_multi` function to the `AnalyzerFactory` class. Implementing the new behaviour in a new function avoids breaking changes and seems to be the most reasonable way to implement this.
Should close #518.

### CODE REVIEW

**Comment by daanraman** [comment]
@SpeedyFireCyclone  "create_multi" is not really descriptive :) - can you change it into something like "create_analyzers_from_configuration_file"? I think it's more immediately clear. Probably @michielmeersmans  would also be well suited for a quick review as he worked on this logic too.

Finally, did you test this against for example the existing use cases configured in production? (sigma + the outlier use cases).

**Comment by SpeedyFireCyclone** [comment]
The naming of the method is to stay in line with the name of the function that is currently used (`create`). I agree that it's not very descriptive, but this is a factory class, and it's a lot clearer when there is additional context.
These changes have not yet been tested thoroughly, but it simply duplicates the functionality that is already there while changing the method signature to return a list of `Analyzers` objects instead of a single one. I'll see if I can do some extra testing and write a unit test for it. 🙂

**Comment by daanraman** [comment]
OK @SpeedyFireCyclone thanks!

Unit tests I would suggest to be comfortable with this PR:
- Configuration file with 0 use cases defined
- Configuration with 1 use case defined
- Configuration with 2 use cases defined
- Configuration with 1 use case that is malformed and another one that is not malformed (to ensure that the non-malformed one in the same file is still accepted)

**Comment by daanraman** [comment]
@SpeedyFireCyclone  can you provide a status update on this? Would be great if we can merge this & include it in the new release! @michielmeersmans these changes should be merged & be part of the RC in the new version

**Comment by SpeedyFireCyclone** [comment]
Test cases are written: I did notice that configparser by default runs in "strict" mode, throwing errors on duplicated keys or sections. This is no issue if there is only one usecase in a file but it does not continue parsing if it encounters such an error. (`configparser.DuplicateSectionError` & `configparser.DuplicateOptionError`)
I've added a way to pass `configparser_options` via the `create_multi` function, what are your thoughts about this? By default it still run in strict mode, is this desirable or should we just let configparse not throw errors for this?

**Pull request merged**
